## SSP Configuration File
## This file is used to configure the SSP service.

## Change the statement from "true" to "false" to enable or disable the feature.

## Seconds to wait before analyzing the services again
check_interval=15
## If enabled, the SSP will stop and unable the services
purge_on_detect=false