#!/bin/bash
set -e
# Detener el servicio antes de desinstalar
echo "Deteniendo y deshabilitando servicio..."
systemctl stop ssp.service
systemctl disable ssp.service

# Eliminacion de rutas del sistema
echo "Eliminando directorios del sistema..."
sudo rm -rf /usr/sbin/ssp_files
sudo rm -f /usr/sbin/ssp
sudo rm -f /share/man/man8/ssp.8
sudo rm -rf /var/log/ssp
sudo rm -rf /lib/systemd/system/ssp.service
exit 0