#!/bin/bash

ssp_files="/usr/local/sbin/ssp_files"
config_file="/etc/ssp.conf"

ROJO='\033[0;31m'
NC='\033[0m' # Sin color
AMARILLO='\033[1;33m'

uninstall() {
    read -rp "Estás seguro de querer desinstalar el servicio? (y/n): " confirmation
    if [[ "$confirmation" =~ ^[Yy]$ ]]; then
        echo -e "${ROJO}Se ha iniciado la desinstalación de SSP${NC}"
        sudo systemctl stop ssp
        sudo systemctl disable ssp
        sudo dpkg -r ssp
        echo "Saltando al prerm..."
    else
        echo -e "${ROJO}Desinstalación cancelada.${NC}"
        exit 1 # Salida por cancelacion
    fi
}
case "$1" in
    -h|--help)
        echo "Opciones disponibles:"
        echo "  -h, --help       Mostrar ayuda"
        echo "  -v, --version    Mostrar versión"
        echo "  -c, --config     Editar el fichero de configuración"
        echo "  -l  --logs       Abrir directorio de logs"
        echo "  -u, --uninstall  Desinstala el servicio y archivos relacionados"
        echo " man,              Abre el manual del servicio"
        ;;
    -v|--version)
        echo "V0.0.0"
        ;;
    -c|--config)
        sudo nano "$config_file"
        #vim "$config_file"
        ;;
    -e|--execute)
        #Ejecucion manual de servicio
        python "$ssp_files/service.py"
        ;;
    -l|--logs)
        cd "/var/log/ssp/" && ls -l
        ;;
    -u|--uninstall)
        uninstall
        ;;
    *)
        echo -e "Error: ${ROJO}'$1'${NC} - Carácter no válido"
        echo -e "Prueba ${AMARILLO}'ssp --help'${NC} o ${AMARILLO}'man ssp'${NC}."
        exit 1 # Salida por cancelacion
        ;;
esac