#!/bin/bash

ssp_files="/usr/local/sbin/ssp_files"
config_file="/etc/ssp.conf"

ROJO='\033[0;31m'
NC='\033[0m' # Sin color
AMARILLO='\033[1;33m'

uninstall() {
    read -rp "Are you sure you want to uninstall? (y/n): " confirmation
    if [[ "$confirmation" =~ ^[Yy]$ ]]; then
        echo -e "${ROJO}Started removing SSP form the system...${NC}"
        sudo systemctl stop ssp
        sudo systemctl disable ssp
        sudo dpkg -r ssp
        echo "Jumping to prerm..."
    else
        echo -e "${ROJO}Uninstallation cancelled.${NC}"
        exit 1 # Salida por cancelacion
    fi
}
case "$1" in
    -h|--help)
        echo "Opciones disponibles:"
        echo "  -h, --help       Show help"
        echo "  -v, --version    Show version"
        echo "  -c, --config     Edit configuration file"
        echo "  -l  --logs       Open logs folder"
        echo "  -u, --uninstall  Desinstala el servicio y archivos relacionados"
        echo " man,              Abre el manual del servicio"
        ;;
    -v|--version)
        echo "V0.0.0"
        ;;
    -c|--config)
        sudo nano "$config_file"
        #vim "$config_file"
        ;;
    -e|--execute)
        #Ejecucion manual de servicio
        python "$ssp_files/service.py"
        ;;
    -l|--logs)
        cd "/var/log/ssp/" && ls -l
        ;;
    -u|--uninstall)
        uninstall
        ;;
    *)
        echo -e "Error: ${ROJO}'$1'${NC} - Invalid character"
        echo -e "Try ${AMARILLO}'ssp --help'${NC} or ${AMARILLO}'man ssp'${NC}."
        exit 1 # Salida por cancelacion
        ;;
esac